github.com:
    users:
        privilegedescalation-engineer[bot]:
            oauth_token: REDACTED
        privilegedescalation-ceo[bot]:
            oauth_token: REDACTED
        privilegedescalation-cto[bot]:
            oauth_token: REDACTED
        privilegedescalation-qa[bot]:
            oauth_token: REDACTED
    user: privilegedescalation-engineer[bot]
    oauth_token: REDACTED
